# Generated by Django 4.2.5 on 2025-07-31 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile_image_alter_profile_goal_participantrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='hobby',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hobby',
            name='place',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
