# Generated by Django 4.2.5 on 2025-12-13 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_requirement_supplier_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='hobby',
            name='end_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hobby',
            name='recurrence',
            field=models.CharField(choices=[('ONCE', 'Once'), ('WEEKLY', 'Weekly'), ('BIWEEKLY', 'Bi-weekly'), ('MONTHLY', 'Monthly')], default='ONCE', max_length=10),
        ),
        migrations.AddField(
            model_name='hobby',
            name='start_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
