# Generated by Django 4.2.5 on 2025-12-13 15:35

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_hobby_schedule_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.profile_image_upload_to),
        ),
        migrations.AddField(
            model_name='profile',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.profile_image_upload_to),
        ),
        migrations.CreateModel(
            name='HobbyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.models.hobby_extra_image_upload_to)),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hobby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.hobby')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
    ]
