# Generated by Django 4.2.5 on 2026-02-16 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_multi_images_and_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='host_request_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='request_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='supplier_decided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='supplier_response_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='address_line1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='supplier',
            name='address_line2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='supplier',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='business_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='supplier',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='supplier',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='supplier',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='supplier',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='supplieritem',
            name='condition',
            field=models.CharField(choices=[('NEW', 'New'), ('LIKE_NEW', 'Like New'), ('GOOD', 'Good'), ('FAIR', 'Fair')], default='GOOD', max_length=20),
        ),
        migrations.AddField(
            model_name='supplieritem',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='supplier_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired')], default='pending', max_length=10),
        ),
    ]
